### ISSUE TITLE
Mod Generator produces invalid TOML file

### ISSUE THREAD

**Issue by Andre601** [QuiltMC/quiltmc.org#212]
The [Mod Generator](https://quiltmc.org/en/usage/generator/) on the QuiltMC website is generating a invalid `libs.versions.toml` file.
Said file has the following issues:

The loom version is defined as `loom` when later on `quilt_loom` is being used for the `version.ref` setting.

The `[libraries]` section is malformed TOML, by having `[` in its own line with a comment in it.

Here is an example of an invalid TOML file using 1.20.4:
```toml
[versions]
# The latest versions are available at https://quiltmc.org/en/usage/latest-versions
minecraft = "1.20.4"
loom = "1.6.5"

quilt_mappings = "1.20.4+build.3"
quilt_loader = "0.25.0"

quilted_fabric_api = "9.0.0-alpha.8+0.97.0-1.20.4"

[# The latest versions are available at https://quiltmc.org/en/usage/latest-versions/
libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilted_fabric_api_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "quilted_fabric_api" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
quilted_fabric_api = ["quilted_fabric_api", "quilted_fabric_api_deprecated"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
```

And here a valid version:
```toml
[versions]
# The latest versions are available at https://quiltmc.org/en/usage/latest-versions
minecraft = "1.20.4"
quilt_loom = "1.6.5"

quilt_mappings = "1.20.4+build.3"
quilt_loader = "0.25.0"

quilted_fabric_api = "9.0.0-alpha.8+0.97.0-1.20.4"

# The latest versions are available at https://quiltmc.org/en/usage/latest-versions/
[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilted_fabric_api_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "quilted_fabric_api" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
[bundles]
quilted_fabric_api = ["quilted_fabric_api", "quilted_fabric_api_deprecated"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
```
