### ISSUE TITLE
Footer is not sticked to bottom

### ISSUE THREAD

**Issue by Mysterious-Dev** [QuiltMC/quiltmc.org#53]
On large screens, the footer is not sticked to bottom

(2560x1440)
![image](https://user-images.githubusercontent.com/40738104/178073124-32748eaa-0d70-4116-a9bf-c6a575ff7aad.png)

**Comment by gdude2002** [comment]
This is just kinda how HTML/CSS works by default.  If a trivial fix is found then I'll do it, but I have no plans to make sweeping changes to the codebase to fix a small display quirk.

**Comment by OroArmor** [comment]
This is some CSS from my webpage where I had the footer stuck to the bottom:
```css
/** Start Footer formatting **/
#main {
  min-height: calc(100% - 50px - 21px);
}

#footer {
  width: 100%;
  background-color: var(--color-dark);
  color: var(--color-medium);
  height: var(--footer-height);
  position: absolute;
  right: 0;
  z-index: -1;
  padding: 15px;
}

#footer-copyright {
  position: relative;
  right: 0;
}

/** End Footer formatting **/
```

**Comment by gdude2002** [comment]
That is an awful lot of hacks for what should be a simple fix.

**Comment by sciwhiz12** [comment]
The following CSS snippet, adapted from my site which was adapted from examples on the web, works to stick the footer to the bottom. It leverages CSS Grid and the fact that there are three elements under `<body>`: one for the header, one for the content, and one for the footer, in that order.

```css
body {
  display: grid;
  grid-template-rows: fit-content(100%) 1fr fit-content(100%);
  min-height: 100vh;
}
```

<details>
<summary>Screenshots of the site in Firefox with DevTools before and after the CSS code is applied through an inline stylesheet. The Responsive Design Mode in the FF DevTools was used to imitate a large screen to showcase the effect, as it does not appear on my screen normally.</summary>

![image](https://user-images.githubusercontent.com/21304337/180861384-365544e3-3904-4ecd-abeb-3a9c40e3dd34.png)
![image](https://user-images.githubusercontent.com/21304337/180861592-50721ffe-ca59-4e72-95e5-cd85f2a37b41.png)

</details>
